package selfupdate

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFindChecksumCoreutilsFormat(t *testing.T) {
	sum := strings.Repeat("ab", 32)
	manifest := sum + "  aksum-linux-amd64\n" + strings.Repeat("cd", 32) + "  SHA256SUMS\n"

	got, err := findChecksum([]byte(manifest), "aksum-linux-amd64")
	if err != nil {
		t.Fatalf("findChecksum: %v", err)
	}
	if got != sum {
		t.Fatalf("got %q, want %q", got, sum)
	}
}

func TestFindChecksumBinaryMode(t *testing.T) {
	sum := strings.Repeat("ef", 32)
	manifest := sum + " *aksum-windows-amd64.exe\n"
	got, err := findChecksum([]byte(manifest), "aksum-windows-amd64.exe")
	if err != nil {
		t.Fatalf("findChecksum: %v", err)
	}
	if got != sum {
		t.Fatalf("got %q, want %q", got, sum)
	}
}

func TestFindChecksumBareDigest(t *testing.T) {
	sum := strings.Repeat("01", 32)
	got, err := findChecksum([]byte(sum+"\n"), "toha3ee_linux_amd64.tar.gz")
	if err != nil {
		t.Fatalf("findChecksum: %v", err)
	}
	if got != sum {
		t.Fatalf("got %q, want %q", got, sum)
	}
}

func TestFindChecksumWithPathsAndComments(t *testing.T) {
	sum := strings.Repeat("12", 32)
	manifest := "# generated by CI\n\ndist/" + "x\n" + sum + "  dist/aksum-darwin-arm64\n"
	got, err := findChecksum([]byte(manifest), "aksum-darwin-arm64")
	if err != nil {
		t.Fatalf("findChecksum: %v", err)
	}
	if got != sum {
		t.Fatalf("got %q, want %q", got, sum)
	}
}

func TestFindChecksumFailures(t *testing.T) {
	tests := []struct {
		name     string
		manifest string
	}{
		{"missing entry", strings.Repeat("ab", 32) + "  other-artifact\n"},
		{"empty manifest", ""},
		{"malformed line", "nothex short\n"},
		{"short digest", "abcd  aksum-linux-amd64\n"},
		{"non-hex digest", strings.Repeat("zz", 32) + "  aksum-linux-amd64\n"},
		{"conflicting entries", strings.Repeat("ab", 32) + "  x\n" + strings.Repeat("cd", 32) + "  x\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := findChecksum([]byte(tt.manifest), "aksum-linux-amd64"); err == nil {
				t.Fatal("expected error, got nil")
			}
		})
	}
}

func TestVerifyFileDigest(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "blob")
	content := []byte("verified-bytes")
	if err := os.WriteFile(path, content, 0o600); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(content)
	want := hex.EncodeToString(sum[:])

	if err := verifyFileDigest(path, want); err != nil {
		t.Fatalf("verifyFileDigest: %v", err)
	}
	if err := verifyFileDigest(path, strings.Repeat("00", 32)); err == nil {
		t.Fatal("expected mismatch error, got nil")
	}
	if err := verifyFileDigest(filepath.Join(dir, "missing"), want); err == nil {
		t.Fatal("expected missing-file error, got nil")
	}
}

func TestFileSHA256UppercaseManifestAccepted(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "b")
	content := []byte("case-insensitive")
	_ = os.WriteFile(path, content, 0o600)
	sum := sha256.Sum256(content)
	upper := strings.ToUpper(hex.EncodeToString(sum[:]))

	got, err := findChecksum([]byte(upper+"  f\n"), "f")
	if err != nil {
		t.Fatalf("findChecksum: %v", err)
	}
	if err := verifyFileDigest(path, got); err != nil {
		t.Fatalf("uppercase digest should verify: %v", err)
	}
}
