package post

import (
	"net"
	"strings"
	"testing"
	"time"

	"github.com/QYVORA/qyvora-toha3ee/internal/store"
)

func TestRenderReportSections(t *testing.T) {
	st := store.New(100)
	now := time.Date(2026, 8, 4, 12, 0, 0, 0, time.UTC)

	h := st.UpsertHost(&store.Host{
		IP:      net.IPv4(10, 0, 0, 5),
		MAC:     net.HardwareAddr{0x00, 0x11, 0x22, 0x33, 0x44, 0x55},
		Vendor:  "Acme",
		Name:    "web01",
		OSGuess: "Linux",
	})
	h.Ports = map[uint16]string{80: "http", 443: "https"}

	st.AddCred(store.Cred{
		Service: "http.post", Username: "admin", Password: "s3cret",
		Host: "web01", VictimIP: "10.0.0.5", Source: "http.harvest", Time: now,
	})
	st.AddSession(store.Session{
		VictimIP: "10.0.0.5", Host: "web01", Captured: now,
		Cookies: map[string]string{"sessionid": "abc123"},
	})
	st.LogEvent("report.test", "ran a test")

	md := renderReport(st, "eth0", now)

	for _, want := range []string{
		"# toha3ee assessment report",
		"## Hosts",
		"**10.0.0.5** `00:11:22:33:44:55` (Acme) name=\"web01\" os=\"Linux\" ports=[80,443]",
		"## Credentials",
		"[http.post] `admin`:`<redacted>`",
		"## Sessions",
		"cookies=`sessionid=abc123`",
		"## Event log",
		"report.test",
		"_generated by toha3ee_",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("report missing %q\n---\n%s", want, md)
		}
	}
}

func TestRenderReportEmpty(t *testing.T) {
	md := renderReport(store.New(100), "eth9", time.Unix(0, 0))
	for _, want := range []string{"_none observed_", "_none captured_", "_empty_"} {
		if !strings.Contains(md, want) {
			t.Errorf("empty report missing %q", want)
		}
	}
}

func TestRenderReportSortsHosts(t *testing.T) {
	st := store.New(100)
	st.UpsertHost(&store.Host{IP: net.IPv4(10, 0, 0, 9)})
	st.UpsertHost(&store.Host{IP: net.IPv4(10, 0, 0, 2)})
	md := renderReport(st, "eth0", time.Now())
	a := strings.Index(md, "**10.0.0.2**")
	b := strings.Index(md, "**10.0.0.9**")
	if a == -1 || b == -1 {
		t.Fatalf("sorted host lines not found")
	}
	if a > b {
		t.Errorf("hosts not sorted: 10.0.0.2 appears after 10.0.0.9")
	}
}

func TestRenderReportRedactsPasswords(t *testing.T) {
	s := store.New(100)
	s.AddCred(store.Cred{
		Service:  "http",
		Username: "admin",
		Password: "s3cretP@ss",
		Host:     "10.0.0.1",
		VictimIP: "10.0.0.2",
		Source:   "http.harvest",
		Time:     time.Now(),
	})

	md := renderReport(s, "eth0", time.Now())
	if strings.Contains(md, "s3cretP@ss") {
		t.Error("markdown report contains plaintext password")
	}
	if !strings.Contains(md, "<redacted>") {
		t.Error("markdown report should contain <redacted> placeholder")
	}
}
